name: 葫芦侠3楼签到

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  
   CRON_TZ=Asia/Shanghai TZ=Asia/Shanghai- cron: '0 9 * * *'

 

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2
      # 安装 Python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: '安装 requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行签到脚本'  
        run: python3 3floor_sign.py 
        env:
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            dingding: ${{ secrets.dingding }}
            SCKEY:   ${{ secrets.SCKEY }}
            notice:   ${{ secrets.notice }} 
